"""add_attorney_marketplace_tables

Revision ID: 3ee459879151
Revises: 4ddb6934627a
Create Date: 2026-03-12 21:52:34.085389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision: str = '3ee459879151'
down_revision: Union[str, None] = '4ddb6934627a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attorney_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('attorney_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attorney_id'], ['labor_attorneys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['attorney_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index('idx_reviews_attorney', 'attorney_reviews', ['attorney_id'], unique=False)
    op.add_column('attorney_cases', sa.Column('chat_session_id', sa.Uuid(), nullable=True))
    op.add_column('attorney_cases', sa.Column('preferred_schedule', sa.JSON(), nullable=True))
    op.add_column('attorney_cases', sa.Column('consultation_fee', sa.Integer(), nullable=False))
    op.alter_column('attorney_cases', 'consultation_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index('idx_cases_attorney', 'attorney_cases', ['attorney_id'], unique=False)
    op.create_index('idx_cases_user', 'attorney_cases', ['user_id', sa.text('created_at DESC')], unique=False)
    op.drop_constraint('attorney_cases_company_id_fkey', 'attorney_cases', type_='foreignkey')
    op.drop_constraint('attorney_cases_attorney_id_fkey', 'attorney_cases', type_='foreignkey')
    op.drop_constraint('attorney_cases_user_id_fkey', 'attorney_cases', type_='foreignkey')
    op.create_foreign_key(None, 'attorney_cases', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'attorney_cases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attorney_cases', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'attorney_cases', 'labor_attorneys', ['attorney_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attorney_cases', 'fee_amount')
    op.drop_index('idx_companies_business_number_active', table_name='companies', postgresql_where='(is_deleted = false)')
    op.create_index('idx_companies_business_number', 'companies', ['business_number'], unique=True)
    op.create_index('idx_companies_owner_id', 'companies', ['owner_id'], unique=False)
    op.alter_column('labor_attorneys', 'specialties',
               existing_type=sa.Text(),
               type_=ARRAY(sa.Text()),
               existing_nullable=False,
               postgresql_using='specialties::text[]')
    op.alter_column('labor_attorneys', 'regions',
               existing_type=sa.Text(),
               type_=ARRAY(sa.Text()),
               existing_nullable=False,
               postgresql_using='regions::text[]')
    op.add_column('labor_attorneys', sa.Column('experience_years', sa.Integer(), nullable=False))
    op.add_column('labor_attorneys', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('labor_attorneys', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('labor_attorneys', 'rating',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('labor_attorneys', 'response_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('labor_attorneys', 'profile_image_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('idx_labor_attorneys_license', table_name='labor_attorneys')
    op.create_index('idx_attorneys_rating', 'labor_attorneys', [sa.text('rating DESC')], unique=False)
    op.create_unique_constraint(None, 'labor_attorneys', ['license_number'])
    op.drop_constraint('labor_attorneys_user_id_fkey', 'labor_attorneys', type_='foreignkey')
    op.create_foreign_key(None, 'labor_attorneys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('labor_attorneys', 'is_available')
    op.drop_index('idx_law_vectors_embedding', table_name='law_vectors', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('payment_history', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('payment_history', 'failure_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('payment_history', 'refund_amount',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('plan_usage', 'usage_month',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint('uq_plan_usage_user_month', 'plan_usage', type_='unique')
    op.drop_index('idx_severance_status', table_name='severance_records', postgresql_where="((status)::text <> 'paid'::text)")
    op.drop_constraint('uq_severance_employee_date', 'severance_records', type_='unique')
    op.create_index('idx_severance_unique', 'severance_records', ['employee_id', 'resign_date'], unique=True)
    op.alter_column('subscriptions', 'monthly_amount',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_kakao_id', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_kakao_id'), 'users', ['kakao_id'], unique=True)
    op.alter_column('work_rules', 'revision_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('work_rules', 'cover_docx_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_work_rules_company_status', table_name='work_rules')
    op.drop_index('idx_work_rules_company_version', table_name='work_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_work_rules_company_version', 'work_rules', ['company_id', 'version'], unique=False)
    op.create_index('idx_work_rules_company_status', 'work_rules', ['company_id', 'status'], unique=False)
    op.alter_column('work_rules', 'cover_docx_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('work_rules', 'revision_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_kakao_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_users_kakao_id', 'users', ['kakao_id'], unique=True)
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.alter_column('subscriptions', 'monthly_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=False)
    op.drop_index('idx_severance_unique', table_name='severance_records')
    op.create_unique_constraint('uq_severance_employee_date', 'severance_records', ['employee_id', 'resign_date'])
    op.create_index('idx_severance_status', 'severance_records', ['status'], unique=False, postgresql_where="((status)::text <> 'paid'::text)")
    op.create_unique_constraint('uq_plan_usage_user_month', 'plan_usage', ['user_id', 'usage_month'])
    op.alter_column('plan_usage', 'usage_month',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('payment_history', 'refund_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=True)
    op.alter_column('payment_history', 'failure_reason',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payment_history', 'amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=False)
    op.create_index('idx_law_vectors_embedding', 'law_vectors', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('labor_attorneys', sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'labor_attorneys', type_='foreignkey')
    op.create_foreign_key('labor_attorneys_user_id_fkey', 'labor_attorneys', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'labor_attorneys', type_='unique')
    op.drop_index('idx_attorneys_rating', table_name='labor_attorneys')
    op.create_index('idx_labor_attorneys_license', 'labor_attorneys', ['license_number'], unique=True)
    op.alter_column('labor_attorneys', 'profile_image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('labor_attorneys', 'response_rate',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('labor_attorneys', 'rating',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('labor_attorneys', 'consultation_fee',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=0),
               existing_nullable=False)
    op.drop_column('labor_attorneys', 'is_active')
    op.drop_column('labor_attorneys', 'experience_years')
    op.alter_column('labor_attorneys', 'specialties',
               existing_type=ARRAY(sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('labor_attorneys', 'regions',
               existing_type=ARRAY(sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('idx_companies_owner_id', table_name='companies')
    op.drop_index('idx_companies_business_number', table_name='companies')
    op.create_index('idx_companies_business_number_active', 'companies', ['business_number'], unique=True, postgresql_where='(is_deleted = false)')
    op.add_column('attorney_cases', sa.Column('fee_amount', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attorney_cases', type_='foreignkey')
    op.drop_constraint(None, 'attorney_cases', type_='foreignkey')
    op.drop_constraint(None, 'attorney_cases', type_='foreignkey')
    op.drop_constraint(None, 'attorney_cases', type_='foreignkey')
    op.create_foreign_key('attorney_cases_user_id_fkey', 'attorney_cases', 'users', ['user_id'], ['id'])
    op.create_foreign_key('attorney_cases_attorney_id_fkey', 'attorney_cases', 'labor_attorneys', ['attorney_id'], ['id'])
    op.create_foreign_key('attorney_cases_company_id_fkey', 'attorney_cases', 'companies', ['company_id'], ['id'])
    op.drop_index('idx_cases_user', table_name='attorney_cases')
    op.drop_index('idx_cases_attorney', table_name='attorney_cases')
    op.alter_column('attorney_cases', 'consultation_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('attorney_cases', 'consultation_fee')
    op.drop_column('attorney_cases', 'preferred_schedule')
    op.drop_column('attorney_cases', 'chat_session_id')
    op.drop_index('idx_reviews_attorney', table_name='attorney_reviews')
    op.drop_table('attorney_reviews')
    # ### end Alembic commands ###
